### ISSUE TITLE
Convexification of network outputs (1D)

### ISSUE THREAD

**Issue by mforets** [JuliaReach/NeuralNetworkAnalysis.jl#112]

**Comment by SebastianGuadalupe** [comment]
Using the initial condition for TORA, I get the interval `[9.79134, 10.2658]` from the controller.

**Comment by SebastianGuadalupe** [comment]
plot comparing set output using Ai2 and sampled output for 10000 samples
![image](https://user-images.githubusercontent.com/49855687/110833844-9fe36400-827b-11eb-8a5e-a3d0b9fb68cf.png)

**Comment by mforets** [comment]
ideas:

- define a function that returns the relative areas between the set-based output and the (CH of) sampled output 

- use the CH of the sampled outputs as an inner approx of the real output
