### ISSUE TITLE
Add vertices of the sampled set in forward_network sampler

### ISSUE THREAD

**Issue by mforets** [JuliaReach/NeuralNetworkAnalysis.jl#120]
https://github.com/JuliaReach/NeuralNetworkAnalysis.jl/blob/d56314f11f4ee19e50fda9884aa9dc72de829d31/src/nnops.jl#L129

**Comment by schillic** [comment]
I meant this only as a check of my hypothesis. If we add the vertices in the regular method, then we can directly use the `VertexSolver`. The additional samples should not change the set then.
