### ISSUE TITLE
Parametric family of toy models with random dynamics

### ISSUE THREAD

**Issue by schillic** [JuliaReach/NeuralNetworkAnalysis.jl#96]
#### Proposal

Add a function `toy_models(n, m; ivp=...)` that returns a list of control problems (described below). `ivp` should be a default random IVP of dimension `n` and `m` control inputs.

#### Purpose

Investigate the precision of the individual steps of the set propagation.

~For affine dynamics we know how to do (almost error-free) set propagation.~
EDIT: Since we currently deal with nonlinear plants only, I take that back. In #104 I create a linear model with a `BlackBoxContinuousSystem` such that we can use our standard algorithm.

#### Control problems

1. controller = identity
     Here we can see the influence of interrupting and re-discretizing.
2. controller = 2 layers with a nonlinear activation function
     Here we can see the influence of a nonlinear activation function
3. controller = 5 layers with nonlinear activation functions
     Here we can see the influence of a somewhat real network

**Comment by mforets** [comment]
sounds good. i don't have a specific model in mind. maybe one of the nonlinear models linearized around some operating condition.
