### ISSUE TITLE
Simulation from extreme points of X0

### ISSUE THREAD

**Issue by schillic** [JuliaReach/NeuralNetworkAnalysis.jl#97]
`simulate` should take a parameter to optionally include the vertices of X0. This should give a better idea about the boundaries.

**Comment by mforets** [comment]
:+1:  this could also be an option at the level of `LazySets.sample`, like `sample(X, 100, include_vertices=true)`

**Comment by schillic** [comment]
https://github.com/JuliaReach/LazySets.jl/pull/2593
